<a href="https://colab.research.google.com/github/shaum09/Python/blob/dev/Python_104.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy

Numpy 1D Arrays

In [ ]:
import numpy as np
np.array([1,-1])*np.array([1,1])

array([ 1, -1])

In [ ]:
np.dot(np.array([1,-1]),np.array([1,1]))

0

Numpy 2D Arrays

In [ ]:
a=np.array([0,1,0,1,0])

b=np.array([1,0,1,0,1])

a*b

array([0, 0, 0, 0, 0])

In [ ]:
a=np.array([0,1])

b=np.array([1,0])

np.dot(a,b)

0

In [ ]:
a=np.array([1,1,1,1,1])

a+10

array([11, 11, 11, 11, 11])

In [ ]:
#correct code to perform matrix multiplication on the matrix A and B
np.dot(A,B)